apiVersion: v1
kind: configmap
metadata:
    name: mysql
    namespace: roboshop
data:
    my.cnf: |
        [mysqld]
        innodb_redo_log_capacity = 2G
---
apiVersion: apps/v1
kind: deployment
metadata: 
    name: mysql
    namespace: roboshop    # Name space where the pods will be created.
    # these are replica-set labels. 
    labels: 
        project: roboshop 
        component: mysql     
        environment: dev
        tier: db
        purpose: deployment
spec:
    replicas: 1
    selector:
        #This is used to select the pods and create the replicaset for those pods. 
        matchLabels:
            project: roboshop 
            component: mysql     
            environment: dev
            tier: db
            purpose: deployment
        #pod definition
    template:
        metadata:
            labels:
                project: roboshop 
                component: mysql     
                environment: dev
                tier: db
                purpose: deployment
        
    spec:
        containers:
            - name: mysql
              image: joindevops/mysql:v1
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: mysql
              readinessProbe:
                tcpSocket:
                    port: 3306
                initialDelaySeconds: 10
                periodSeconds: 5
                failureThreshold: 3
                successThreshold: 1
              livenessProbe:
                tcpSocket:
                    port: 3306
                initialDelaySeconds: 20
                periodSeconds: 10
                failureThreshold: 5
                successThreshold: 2
              ports:
                - containerPort: 3306 # its a must to expose the port for the service to connect to the pod.
              volumeMounts:
                - name: mysql-config
                  mountPath: /etc/mysql/conf.d/my.cnf
                  subPath: my.cnf
        volumes:
            - name: mysql-config
              configMap:
                name: mysql
# ------------
#creating a servicefor mysql pods.
apiVersion: v1
kind: service
metadata:
    name: mysql
    namespace: roboshop # Name space where the pods will be created.
    # these are service labels.
    labels:
        project: roboshop 
        component: mysql     
        environment: dev
        tier: db
        purpose: service
    port:
        - name: mysql
          port: 3306  # service port which will be used by other pods to connect to this service.
          targetPort: 3306 # pod port which will be used by the service to connect to the pod.
          protocol: TCP

